import { catchAsync } from "../../common/errors/catchAsync.js";

export const createUser = catchAsync(async(req,res,next)=>{

})
export const login = catchAsync(async(req,res,next)=>{
    
})
export const updateprofile = catchAsync(async(req,res,next)=>{
    
})
export const deleteUser = catchAsync(async(req,res,next)=>{
    
})
export const findUserOrders = catchAsync(async(req,res,next)=>{
    
})
export const findOneOrder = catchAsync(async(req,res,next)=>{
    
})